package.json, src/components/course-graph.js, src/components/templates/guide-template.js, src/styles/components.scss, src/utils/course-namer.js, yarn.lock
This:
```js
<CourseGraph
reqs={[
["CMP401", "CS445"],
["CS441", "CS1502"],
["CS441", "CS1501"],
["CS445", "CS447", { type: "coreq" }],
["CS445", "CS1502"],
["CS445", "CS449"],
["CS447", "CS449", { type: "coreq" }],
["CS445", "CS1501"],
["CS1501", "CS1550"],
["CS447", "CS1550"],
["CS449", "CS1550"],
]}
/>
```
Outputs
And, it is an interactable, stylable SVG. 
Right now, clicking the link will take you to its course page. We can customize this later to be like, show the course info on hover or something.
Also, it needs more style adjustments.
=> Start the course graph generator component

src/pages/guides/study-abroad.md
basic study abroad guide done, with emphasis on Exchange Programs since those require a ton of work to get approved.
=> Wrote v1 of Study Abroad Guide

src/components/feedback.js, src/components/templates/blog-post-layout.js, src/styles/components.scss, src/styles/tailwind.scss
uses netlify forms to post straight to netlify, so no server needed, so its fast
closes #67
=> Feedback Form

src/components/courses/requirements.js, src/styles/components.scss
=> Support course requirements that have "or"s

src/pages/guides/uta.md
thanks @glu99331 for writing this 
closes #66
=> How to UTA guide

gatsby-config.js, package.json, src/utils/algolia.js
accidentally was double uploading records to Algolia, because i had enablePartialOn
thought that would make it faster, but realized that that would keep stale data in it :(
=> Fix Algolia Search Bug

src/components/footer.js, src/components/header.js, src/pages/about.js, src/styles/layout.scss
1. About page (did not spend a lot of time working on the prose of that, but it can be changed)
2. Footer has links to other pages
and shows up on mobile now
also 
small change but the header is on now
closes #33 
closes #131
=> About Page + Better Footer 

src/components/table-of-contents.js, src/components/templates/blog-post-layout.js
=> [Hotfix] Table of Contents + Edit on GitHub bug

src/components/courses/course-graph.js
on mobile make course graph in scheduling page scroll
close #145
=> [Hotfix] Scrollable course graph

src/components/sitemap-list.js, src/pages/guides.js, src/pages/sitemap.js
Just putting all of the guides on the guides page, so its easy for people to see what we have. The sitemap can probably be updated to look nicer, but for wiki v1 I think this is ok
close #143
=> Updates /guides/ to have whole guides listing

src/components/footer.js, src/components/sitemap-list.js, src/components/templates/courses-template.js, src/pages/about.js, src/pages/course-review.js, src/pages/feedback.js, src/pages/guides.js
close #161 
close #12 
Looks a lot nicer now
=> Embed Google Forms

src/guides/career/index.md, src/guides/career/team-matching.md
close #42 
This is the first guide I've written
=> Team Matching

src/components/feedback.js, src/components/templates/blog-post-layout.js, src/styles/components.scss
It looked a lil off to me. Like the way it looks more now and it says 'sending' while it is sending
Also, dont show feedback or edit on github stuff on index pages
close #92
=> Improve Feedback

src/components/courses/course-graph.js, src/components/courses/course-listing.js, src/guides/academics/scheduling.mdx
=> Course Explorer Page is a little cleaner

src/guides/academics/index.md, src/guides/career/index.md, src/guides/misc/index.md, src/guides/zero-to-offer/index.md, src/utils/sitegraph-generator.js
For some reason relative linking causes a bug in the browser sometimes for some pages (PR #162) for more details
Just getting rid of them and making it so they are not allowed anymore
=> I hate relative linking

src/data/requirements.json
finally lol sorry yall
close #118
=> Fixing parsing errors for course requirements

gatsby-config.js, package.json, src/components/feedback.js, src/components/footer.js, src/styles/tailwind.scss, tailwind.config.js, yarn.lock
- Purge CSS via tailwind (removes unused classes which will reduce css size a bunch)
- Remove font awesome (only using the heart, so its a waste of a dependency)
- actually was using it for the feedback widget too and did not notice until it didnt build, but removed it anyways
- I think loading d3 and dagre from the course graph component is fine since the mdx file uses that as a shortcode, idk if more components are added then those should be lazy loaded in probably
- make feedback buttons look a lil nicer
close #89
=> Optimize CSS

src/guides/career/team-matching.md, src/guides/skills/index.md, src/guides/skills/personal-website.md, src/guides/zero-to-offer/index.md
=> Personal Website

src/components/courses/course-listing.js, src/components/courses/requirements.js, src/data/autogenerated_course_info.json, src/data/requirements.json
OCD , some of them said "PREQ" others said "PRE-REQ"
=> [Hotfix] Clean requirements / course descriptions a little 

src/guides/academics/high-school.md
=> Created high school guide

src/guides/career/job-success.md
=> Succeed at your job

src/guides/academics/capstone.md
closes #69 
git is pain
@Zmwang622 @varughese
=> Completed capstone.md

docs/CODEOWNERS, src/components/templates/courses-template.js, src/guides/career/mock-interview.md, src/guides/career/resume.md, src/guides/zero-to-offer/ace-your-interview.md, src/guides/zero-to-offer/building-your-case.md, src/guides/zero-to-offer/index.md, src/guides/zero-to-offer/mindset.md, src/guides/zero-to-offer/overview.md, src/guides/zero-to-offer/post-interview.md, src/guides/zero-to-offer/potpourri.md, src/pages/guides.js, src/utils/sitegraph-generator.js
most anticipated guides of the new decade
=> ZERO TO OFFER!!!!!!!!!!!!

src/guides/academics/scheduling.mdx
=> Scheduling

src/components/templates/blog-post-layout.js, src/components/templates/guide-template.js, src/guides/academics/prospective/infosci-vs-cs.md
=> don't run markdown files

src/guides/skills/clubs.md
Went to add in a RAS page and noticed that there was already a section. I fleshed it out a bit more because I was there and had gone through the trouble of setting up.
Mostly added some more description and links.
=> Add some more links/info to RAS guide.

src/guides/academics/prospective/transfer-students.md
Typed this out quickly. Not sure 100% what you're looking for and this is fairly informal. Feedback welcome & I can re-draft it tonight. Thanks!
=> Guide for Perspective Transfers

src/components/search/hit-comps.js
the search result for courses has more margin bottom for some reason now
fix that
=> [Hotfix] CSS bug on searching for courses

src/data/categories.json
=> Fix broken link on courses page

src/guides/academics/registration/cross-register.md
You can call me a life saver for this one guys.
=> Fix single typo in Cross Registration guide

gatsby-config.js, package.json, src/components/table-of-contents.js, src/components/templates/guide-template.js, src/styles/components.scss, yarn.lock
Addressing #128 and #242. 
Decided to add h5 and h6 to the autolinker, as I think we should follow the convention set by HTML for 6 depth levels of headers.
Still working on how to best implement styling change to avoid TOC overlap with guide content, which can happen quite often without contrived examples. I'm thinking that it might require some amount of either layout refactoring or some additional styling props to layouts..
=> Add active heading highlight and fix dead links for table of contents

src/guides/academics/majors/comp-bio.md
Updated with: chem, ochem, bio, bio lab UTA information; wording consistency; more information on capstone; made recommended 4 year plan more readable
=> Updating comp bio guide v.3

src/components/professor-tooltip.js, src/components/testimonial.js, src/styles/components.scss
Break professor onto new line for smaller displays and disable tooltip popups for mobile (the link to RMP stays enabled).
=> Improve mobile compatibility and add touchscreen support to professor tooltips

src/components/courses/course-listing.js
Just a fun minor addition. Title explains it all.
Closes #235
=> Add support for double-click quick navigation in course view

src/guides/career/career-fair.md
Closes #251 
Ming pointed out that the code blocks looked bad in the career fair guide, but imo there's no reason we should be using code blocks for just text. Let's move to blockquotes instead.
=> Move from code block to blockquotes in career fair guide

src/guides/career/resume.md, src/guides/skills/getting-started-with-x/hackathons.md, src/guides/skills/getting-started-with-x/index.md, src/guides/skills/getting-started-with-x/projects.md, src/guides/zero-to-offer/building-your-case.md
Related: #40 
Add a section to skills for Getting Started guides that focus on helping people to start learning things.
=> Add "Getting Started with X" section to skills

src/guides/zero-to-offer/mindset.md
Fixed the hyperlink to Blind as noted in #257 as well as others in the same section.
=> Fix hyperlinks to Blind, etc.

src/guides/skills/getting-started-with-x/game-dev.md
Thanks to Alex Bailey and Alejandro Ciuba for contributing to this -- it was originally published to https://github.com/JeffTheSquid/CSC-Game-Dev-Start and I made a few changes
=> Add Getting Started with Game Development guide

src/guides/skills/getting-started-with-x/git.md
Pro Git is really popular so I figure we add it as a resource
=> Add git textbook

src/guides/career/freshman-sophomore-opportunities.md, src/guides/career/leetcode-summer.md, src/guides/career/resume-checklist.md, src/guides/career/study-plan.md
- https://github.com/PittCSWiki/pittcswiki/issues/183
- https://github.com/PittCSWiki/pittcswiki/issues/187
- https://github.com/PittCSWiki/pittcswiki/issues/240
I created a page for freshman / sophomore specific opportunities based on Ming's reddit post: https://old.reddit.com/r/csMajors/comments/htusm4/internships_for_freshmansophomores/fyj59dq/?context=3
I created a page with links to all the leetcode problems and solutions. 
I created a page serving as a resume checklist.
=> Add three new pages to career guides

src/guides/academics/scheduling.mdx
Added a case by case description with a few caveats.
=> Updating 7 vs 401 faq

README.md, docs/setup-dev.md
Add dev guide link (which instructs on how to set up development environment / add guides) to main README
=> Add dev guide link to README

src/guides/academics/majors/dnid.md
Crystal Li might add some changes this weekend but she gave me the go-ahead to make the PR and publish this.
Of course, let me know if I need to change anything!
=> Digital Narrative and Interactive Design Major Guide

src/guides/academics/succeed-in-course-x/succeed-in-441.md
i needed to remove the latex because it didn't embed correctly on the website.
=> removing all latex

src/guides/academics/scheduling.mdx
Put each professor listed for each course along with their ratemyprofessor link
=> Add Professor Column and additional schedule

src/guides/skills/clubs.md
Added some updated info about CSC programs. Mostly just learning how to contribute to the wiki and using this as a starting place.
=> Update CSC programs information

docs/templates/succeed-in-course-x-template.md
adding a template for the succeed-in-course-x guides.
=> adding succeed in course x template in docs

docs/CODEOWNERS
Codeowners is a bottleneck for merging PRs rn so I'm adding people
=> Update CODEOWNERS to include more people

src/guides/career/general-college-advice.md
I like the sound of "Pay it forward" over "Help Others"
=> Rename section title

package.json, yarn.lock
=> Delete node-sass and replace with sass

src/guides/academics/registration/capstone.md
SCI now requests that students meet with their assigned faculty mentor, rather than finding a random faculty sponsor.
=> faculty sponsor -> faculty mentor

src/guides/academics/majors/comp-bio.md
Extra info on CS 1640 vs BIOSC 1640 and BIOSC 1630 seminar now that I'm taking the last comp bio major requirements.
=> Comp bio guide updated seminar and capstone and co req info

src/guides/skills/getting-started-with-x/rust.md
Finally got around to tidying up the guide I wrote in November.
Let me know how it looks or if there's anything I should change.
=> Intro to Rust Guide

src/components/templates/blog-post-layout.js
cant wait to bump this up again in 600 days
=> only show freshness disclaimer if 1000 days old

.github/workflows/combine-prs.yml
We have a lot of Dependabot PRs. This GitHub Action allows us to merge them into a single PR.
https://github.com/hrvey/combine-prs-workflow
=> Add GitHub Action for combining Dependabot PRs

src/guides/career/resume.md
People keep adding their phone numbers to resume but it's really just a wasted line
=> Updated the article on resume writing

gatsby-node.js, src/components/testimonial.js, src/utils/sitegraph-generator.js, yarn.lock
Added a condition to restrict reviews shown to those written up to 4 years in the past.
=> Limit Course Reviews to Up to 4 years in The Past

src/guides/career/product-management.md
closes #207 #397 
Finally lol, an article on Product Management. I wanted to take a fundamentals approach as opposed to focusing on what the role actually does (enough of the '6 figures without coding' yapping online!!)
=> Create PM article

docs/setup-dev.md
While reading the setup doc, I noticed a small typo and fixed it.
=> Fix typo in setup-dev.md
